### ISSUE TITLE
Log in with MicroAccount doesn't work when launch as a service

### ISSUE THREAD

**Issue by xywc-s** [roydejong/WSLHostsUpdater#1]
It's a superb tool, but I've had some problems using it.
When I launch it as an app, it works perfectly.
But when I start it as a service, it doesn't work.
`sc.exe create "WSLHostsUpdater" binpath="E:\WSLHostsUpdater.exe" start=delayed-auto obj=MciroAccount\email password=MciroAccountPassword`
By the way, my system uses Microsoft accounts and Windows Hello to sign in. System version is win11-22621.

**Comment by roydejong** [comment]
When using the `sc` command, make sure you're running it from an command window running as administrator.

If you're getting some kind of error from `sc`, would you mind sharing it?

If you believe the problem is with the authentication, it may be worth creating the service without account credentials, and then trying to configure it manually from the Services window where you can do it interactively:

![image](https://user-images.githubusercontent.com/6772638/172343809-6e93185d-cb34-4f12-ab59-1a0dbd72bbb8.png)
